#!/usr/bin/env bash
#
# Per-instance setup. Idempotent: safe to run on every boot, and safe to run twice.
#
# This is a separate script rather than entrypoint code because Vast's SSH and Jupyter
# launch modes replace the image's entrypoint with their own startup. In those modes put
#
#     bash /opt/ft/onstart.sh
#
# in the instance's on-start script field. In Entrypoint mode, and under a plain
# `docker run`, entrypoint.sh calls it for you.
set -euo pipefail

WORKSPACE="${WORKSPACE:-/workspace}"
log() { printf '[ft-onstart] %s\n' "$*"; }

# --- 1. Persistent layout ----------------------------------------------------------
# Weights, the FTW builds converted from them, the bandwidth profile and the per-model
# cache costs ft-man measures all live here. On a destroy-after-use rental none of it
# survives, which is why the FTW build belongs in a private HF repo — see docker/README.md.
mkdir -p \
  "$WORKSPACE/models" \
  "$WORKSPACE/hf/hub" \
  "$WORKSPACE/cache" \
  "$WORKSPACE/state/ft-man" \
  "$WORKSPACE/config/ft-man"

# --- 2. Make the environment visible to interactive shells -------------------------
# Vast injects instance environment variables into the on-start process, but its docs are
# explicit that they are NOT visible inside SSH, tmux or Jupyter sessions by default.
# HF_TOKEN arrives exactly that way, so without this bridge ft-man would report no token
# on an instance that was given one, and gated downloads would 401 for no visible reason.
#
# This writes the token to disk inside the running container. That is the container's own
# filesystem on a machine you have rented, never a layer of the published image.
PROFILE=/etc/profile.d/10-freetoken.sh
{
  echo '# Generated by /opt/ft/onstart.sh on every boot. Do not edit.'
  for v in HF_TOKEN HUGGING_FACE_HUB_TOKEN HF_HOME XDG_CACHE_HOME \
           FT_MAN_STATE_DIR FT_MAN_CONFIG_DIR VIRTUAL_ENV CUDA_HOME WORKSPACE PATH; do
    if [ -n "${!v:-}" ]; then printf 'export %s=%q\n' "$v" "${!v}"; fi
  done
} > "$PROFILE"
chmod 0644 "$PROFILE"

# profile.d covers login shells. Interactive non-login shells (what `docker exec -it`
# and some SSH invocations give you) read .bashrc instead, so point that at it too.
BASHRC="${HOME:-/root}/.bashrc"
if ! grep -qsF "$PROFILE" "$BASHRC"; then
  printf '\n# FreeToken environment, written by /opt/ft/onstart.sh\n[ -r %s ] && . %s\n' \
    "$PROFILE" "$PROFILE" >> "$BASHRC"
fi

# --- 3. ft-man configuration -------------------------------------------------------
# Written once. Edits survive, because a rented instance is where you actually tune this.
CFG="$WORKSPACE/config/ft-man/config.toml"
if [ ! -f "$CFG" ]; then
  cat > "$CFG" <<'TOML'
# Written once by /opt/ft/onstart.sh. Edit freely; it is never overwritten.

[freetoken]
venv = "/opt/freetoken/venv"

[library]
# Pinned, not inherited from HF_HOME. Vast's documentation is explicit that instance
# environment variables are NOT visible inside SSH, tmux or Jupyter sessions, and the same
# is true of a session opened before this file was written. A cache derived from the
# environment therefore resolves to an empty one under $HOME, and ft-man reports a library
# of nothing on an instance holding hundreds of gigabytes -- while pricing a download
# against the container's root filesystem instead of /workspace.
hub_cache = "/workspace/hf/hub"
roots = ["/workspace/models"]
download_dir = "/workspace/models"
# FTW builds. Deliberately outside the cache: that tree belongs to huggingface_hub, and a
# directory it did not write is invisible to `hf cache scan` and at risk from
# `hf cache delete`.
ftw_dir = "/workspace/models"

[server]
# Loopback, deliberately. `ft serve` has no authentication of any kind, so a wildcard bind
# plus a mapped port would publish an open inference endpoint on a public IP. Caddy reaches
# it here and republishes it with the Instance Portal's TLS and auth; ft-man polls it here
# too. Outside Vast, reach it with `ssh -N -L 1919:127.0.0.1:1919 <host>`.
host = "127.0.0.1"
port = 1919

[web]
# Loopback for the same reason as [server] above: ft-man web can start and stop the engine,
# delete checkpoints and write files, and its own auth is opt-in. The ft-man-web supervisor
# program (docker/supervisor/) serves it here; front it with Caddy the same way as the
# engine's 1919 -- see docker/README.md -- rather than mapping 7979 directly.
listen = "127.0.0.1:7979"
TOML
  log "wrote $CFG"
fi

# --- 4. Report ---------------------------------------------------------------------
if command -v nvidia-smi >/dev/null 2>&1; then
  log "$(nvidia-smi --query-gpu=name,driver_version --format=csv,noheader | paste -sd'; ')"
  # CUDA 13 needs driver r580 or newer. On Vast this is a property of the host you rented,
  # not of this image, and it is better to learn it now than during weight load.
  drv="$(nvidia-smi --query-gpu=driver_version --format=csv,noheader | head -1 | cut -d. -f1)"
  if [ -n "$drv" ] && [ "$drv" -lt 580 ]; then
    log "WARNING: driver $drv is below the r580 this CUDA 13 build needs. Expect load failures."
  fi
else
  log "WARNING: no nvidia-smi. This instance has no GPU visible to the container."
fi
log "ft:     $(ft --version 2>&1 | head -1)"
log "ft-man: $(ft-man --version 2>&1 | head -1)"
log "ft-man web is supervised and listening on 127.0.0.1:7979 -- see docker/README.md to front it"
log "ready. run: ft-man --doctor"
